biomes = {
    # 🌱 GRASSLANDS (Starter)
    "Grasslands": {
        "monsters": [
            {"name": "Slime", "health": 20, "attack": 5, "exp": 20, "gold": 10},
            {"name": "Wild Rabbit", "health": 15, "attack": 4, "exp": 15, "gold": 8},
            {"name": "Goblin Scout", "health": 25, "attack": 6, "exp": 25, "gold": 12},
            {"name": "Stray Dog", "health": 22, "attack": 5, "exp": 20, "gold": 10},
            {"name": "Field Bandit", "health": 30, "attack": 7, "exp": 30, "gold": 15},
            {"name": "Horned Beetle", "health": 35, "attack": 6, "exp": 28, "gold": 14},
            {"name": "Mud Crawler", "health": 28, "attack": 6, "exp": 26, "gold": 13},
            {"name": "Grass Sprite", "health": 18, "attack": 7, "exp": 24, "gold": 12},
            {"name": "Tiny Boar", "health": 32, "attack": 8, "exp": 30, "gold": 16},
            {"name": "Broken Knight", "health": 40, "attack": 9, "exp": 35, "gold": 18},
            {"name": "Rusty Drone", "health": 25, "attack": 7, "exp": 28, "gold": 14},
            {"name": "Cursed Crow", "health": 20, "attack": 9, "exp": 26, "gold": 13},
            {"name": "Lost Farmer Spirit", "health": 30, "attack": 8, "exp": 32, "gold": 15},
            {"name": "Stone Rat", "health": 35, "attack": 7, "exp": 30, "gold": 15},
            {"name": "Wind Imp", "health": 22, "attack": 10, "exp": 34, "gold": 17},
        ],
        "loot": ["Small Potion", "Herb", "Old Coin", "Torn Cloth"],
    },
    # 🌲 FOREST (Mid)
    "Forest": {
        "monsters": [
            {"name": "Wolf", "health": 30, "attack": 8, "exp": 30, "gold": 15},
            {"name": "Forest Spider", "health": 25, "attack": 9, "exp": 28, "gold": 14},
            {"name": "Orc Warrior", "health": 45, "attack": 12, "exp": 40, "gold": 20},
            {"name": "Treant Sapling", "health": 50, "attack": 10, "exp": 45, "gold": 22},
            {"name": "Poison Snake", "health": 20, "attack": 11, "exp": 30, "gold": 18},
            {"name": "Shadow Stalker", "health": 35, "attack": 13, "exp": 50, "gold": 25},
            {"name": "Wood Bandit", "health": 38, "attack": 11, "exp": 36, "gold": 18},
            {"name": "Thorn Beast", "health": 55, "attack": 12, "exp": 48, "gold": 24},
            {"name": "Forest Spirit", "health": 40, "attack": 14, "exp": 52, "gold": 26},
            {"name": "Moss Golem", "health": 60, "attack": 11, "exp": 55, "gold": 28},
            {"name": "Venom Lizard", "health": 33, "attack": 13, "exp": 42, "gold": 21},
            {"name": "Dark Elf Scout", "health": 37, "attack": 15, "exp": 50, "gold": 25},
            {"name": "Rotting Stag", "health": 45, "attack": 12, "exp": 47, "gold": 23},
            {"name": "Feral Druid", "health": 42, "attack": 14, "exp": 53, "gold": 27},
            {"name": "Whispering Shade", "health": 38, "attack": 16, "exp": 58, "gold": 30},
        ],
        "loot": ["Medium Potion", "Forest Gem", "Spider Silk", "Enchanted Leaf"],
    },
    # 🏔️ MOUNTAINS (Hard)
    "Mountains": {
        "monsters": [
            {"name": "Goblin Raider", "health": 40, "attack": 10, "exp": 40, "gold": 20},
            {"name": "Stone Golem", "health": 70, "attack": 12, "exp": 60, "gold": 30},
            {"name": "Mountain Wolf", "health": 50, "attack": 11, "exp": 45, "gold": 22},
            {"name": "Ice Bat", "health": 30, "attack": 9, "exp": 35, "gold": 18},
            {"name": "Rock Serpent", "health": 60, "attack": 14, "exp": 70, "gold": 35},
            {"name": "Frost Giant Scout", "health": 80, "attack": 15, "exp": 80, "gold": 40},
            {"name": "Cliff Harpy", "health": 45, "attack": 13, "exp": 50, "gold": 25},
            {"name": "Avalanche Spirit", "health": 55, "attack": 16, "exp": 65, "gold": 32},
            {"name": "Ironback Yak", "health": 75, "attack": 12, "exp": 68, "gold": 34},
            {"name": "Crystal Spider", "health": 50, "attack": 15, "exp": 60, "gold": 30},
            {"name": "Frozen Knight", "health": 85, "attack": 17, "exp": 90, "gold": 45},
            {"name": "Blizzard Wraith", "health": 60, "attack": 18, "exp": 85, "gold": 42},
            {"name": "Peak Guardian", "health": 90, "attack": 20, "exp": 100, "gold": 50},
            {"name": "Snow Panther", "health": 55, "attack": 16, "exp": 70, "gold": 35},
            {"name": "Storm Eagle", "health": 65, "attack": 19, "exp": 95, "gold": 48},
        ],
        "loot": ["Large Potion", "Mountain Ore", "Ice Crystal", "Ancient Relic"],
    },
    # 🔥 SCORCHING DESERT
    "Desert": {
        "monsters": [
            {"name": "Sand Bandit", "health": 45, "attack": 13, "exp": 50, "gold": 25},
            {"name": "Scorpion", "health": 35, "attack": 15, "exp": 48, "gold": 24},
            {"name": "Fire Lizard", "health": 50, "attack": 16, "exp": 55, "gold": 28},
            {"name": "Dust Wraith", "health": 40, "attack": 18, "exp": 60, "gold": 30},
            {"name": "Cactus Beast", "health": 65, "attack": 14, "exp": 62, "gold": 31},
            {"name": "Sun Priest", "health": 55, "attack": 17, "exp": 70, "gold": 35},
            {"name": "Desert Wolf", "health": 48, "attack": 15, "exp": 58, "gold": 29},
            {"name": "Ancient Scarab", "health": 60, "attack": 14, "exp": 65, "gold": 32},
            {"name": "Heat Elemental", "health": 70, "attack": 18, "exp": 75, "gold": 38},
            {"name": "Mirage Assassin", "health": 45, "attack": 20, "exp": 80, "gold": 40},
            {"name": "Sand Golem", "health": 85, "attack": 16, "exp": 90, "gold": 45},
            {"name": "Blazing Hawk", "health": 50, "attack": 19, "exp": 85, "gold": 42},
            {"name": "Nomad Raider", "health": 60, "attack": 17, "exp": 72, "gold": 36},
            {"name": "Desert Spirit", "health": 55, "attack": 21, "exp": 88, "gold": 44},
            {"name": "Molten Serpent", "health": 75, "attack": 22, "exp": 95, "gold": 48},
        ],
        "loot": ["Heat Core", "Desert Relic", "Golden Sand", "Rare Gem"],
    },
    # ❄️ ICY PLAINS
    "Ice Plains": {
        "monsters": [
            {"name": "Ice Wolf", "health": 50, "attack": 15, "exp": 60, "gold": 30},
            {"name": "Frost Spider", "health": 40, "attack": 14, "exp": 55, "gold": 28},
            {"name": "Glacier Golem", "health": 90, "attack": 18, "exp": 85, "gold": 42},
            {"name": "Frozen Spirit", "health": 60, "attack": 20, "exp": 80, "gold": 40},
            {"name": "Snow Beast", "health": 70, "attack": 17, "exp": 75, "gold": 38},
            {"name": "Ice Knight", "health": 85, "attack": 19, "exp": 90, "gold": 45},
            {"name": "Blizzard Imp", "health": 45, "attack": 18, "exp": 65, "gold": 32},
            {"name": "Frozen Harpy", "health": 55, "attack": 17, "exp": 70, "gold": 35},
            {"name": "Polar Bear", "health": 100, "attack": 16, "exp": 95, "gold": 48},
            {"name": "Ice Wraith", "health": 65, "attack": 21, "exp": 88, "gold": 44},
            {"name": "Shard Beast", "health": 75, "attack": 20, "exp": 92, "gold": 46},
            {"name": "Snow Assassin", "health": 60, "attack": 22, "exp": 95, "gold": 48},
            {"name": "Frost Giant", "health": 110, "attack": 22, "exp": 110, "gold": 55},
            {"name": "Avalanche Beast", "health": 95, "attack": 21, "exp": 100, "gold": 50},
            {"name": "Ice Dragonling", "health": 105, "attack": 23, "exp": 115, "gold": 58},
        ],
        "loot": ["Ice Core", "Frozen Relic", "Crystal Shard", "Ancient Ice"],
    },
    # ☠️ VENOMOUS SWAMP
    "Swamp": {
        "monsters": [
            {"name": "Swamp Slime", "health": 45, "attack": 12, "exp": 50, "gold": 25},
            {"name": "Poison Frog", "health": 30, "attack": 16, "exp": 48, "gold": 24},
            {"name": "Bog Beast", "health": 70, "attack": 14, "exp": 65, "gold": 32},
            {"name": "Swamp Witch", "health": 60, "attack": 18, "exp": 70, "gold": 35},
            {"name": "Toxic Serpent", "health": 50, "attack": 20, "exp": 75, "gold": 38},
            {"name": "Rot Zombie", "health": 65, "attack": 15, "exp": 68, "gold": 34},
            {"name": "Mud Golem", "health": 80, "attack": 13, "exp": 72, "gold": 36},
            {"name": "Plague Rat", "health": 40, "attack": 17, "exp": 55, "gold": 28},
            {"name": "Swamp Spirit", "health": 55, "attack": 19, "exp": 78, "gold": 39},
            {"name": "Venom Spider", "health": 48, "attack": 21, "exp": 80, "gold": 40},
            {"name": "Rotting Knight", "health": 75, "attack": 18, "exp": 85, "gold": 42},
            {"name": "Toxic Elemental", "health": 90, "attack": 22, "exp": 95, "gold": 48},
            {"name": "Swamp Hydra", "health": 110, "attack": 23, "exp": 110, "gold": 55},
            {"name": "Plague Doctor", "health": 70, "attack": 20, "exp": 88, "gold": 44},
            {"name": "Death Leech", "health": 60, "attack": 24, "exp": 100, "gold": 50},
        ],
        "loot": ["Toxic Core", "Swamp Relic", "Venom Sac", "Dark Herb"],
    },
    # 🌌 SHADOW REALM
    "Shadow Realm": {
        "monsters": [
            {"name": "Shadow Imp", "health": 50, "attack": 18, "exp": 70, "gold": 35},
            {"name": "Dark Wraith", "health": 65, "attack": 22, "exp": 85, "gold": 42},
            {"name": "Night Stalker", "health": 55, "attack": 24, "exp": 90, "gold": 45},
            {"name": "Void Beast", "health": 90, "attack": 20, "exp": 95, "gold": 48},
            {"name": "Abyss Knight", "health": 100, "attack": 23, "exp": 110, "gold": 55},
            {"name": "Phantom Assassin", "health": 70, "attack": 26, "exp": 105, "gold": 52},
            {"name": "Dark Sorcerer", "health": 80, "attack": 25, "exp": 100, "gold": 50},
            {"name": "Shadow Dragonling", "health": 110, "attack": 24, "exp": 115, "gold": 58},
            {"name": "Void Spider", "health": 60, "attack": 23, "exp": 95, "gold": 48},
            {"name": "Nightmare Beast", "health": 120, "attack": 27, "exp": 130, "gold": 65},
            {"name": "Dread Knight", "health": 130, "attack": 26, "exp": 140, "gold": 70},
            {"name": "Soul Reaper", "health": 90, "attack": 28, "exp": 150, "gold": 75},
            {"name": "Void Titan", "health": 150, "attack": 30, "exp": 170, "gold": 85},
            {"name": "Abyssal Horror", "health": 140, "attack": 29, "exp": 165, "gold": 82},
            {"name": "Eternal Shade", "health": 135, "attack": 31, "exp": 180, "gold": 90},
        ],
        "loot": ["Void Core", "Shadow Relic", "Dark Crystal", "Soul Fragment"],
    },
}

