claimguardians = {
    "Grasslands": {
        "name": "Troll King",
        "health": 200,
        "attack": 25,
        "exp": 200,
        "gold": 150,
        "ability": "Smash",
        "loot": ["Legendary Amulet"],
    },
    "Forest": {
        "name": "Ancient Treant",
        "health": 250,
        "attack": 30,
        "exp": 250,
        "gold": 200,
        "ability": "Smash",
        "loot": ["Epic Staff"],
    },
    "Mountains": {
        "name": "Dragon Lord",
        "health": 300,
        "attack": 35,
        "exp": 300,
        "gold": 300,
        "ability": "Fire Breath",
        "loot": ["Dragon Slayer Sword"],
    },
    "Desert": {
        "name": "Sun-Scorched Colossus",
        "health": 340,
        "attack": 38,
        "exp": 360,
        "gold": 360,
        "ability": "Fire Breath",
        "loot": ["Heat Core", "Desert Relic", "Rare Gem"],
    },
    "Ice Plains": {
        "name": "Glacier Crown Regent",
        "health": 370,
        "attack": 40,
        "exp": 390,
        "gold": 390,
        "ability": "Smash",
        "loot": ["Ice Core", "Frozen Relic", "Ancient Ice"],
    },
    "Swamp": {
        "name": "Hydra of the Black Mire",
        "health": 410,
        "attack": 42,
        "exp": 430,
        "gold": 430,
        "ability": "Smash",
        "loot": ["Toxic Core", "Swamp Relic", "Venom Sac"],
    },
    "Shadow Realm": {
        "name": "The Claim-Eater",
        "health": 460,
        "attack": 45,
        "exp": 520,
        "gold": 520,
        "ability": "Fire Breath",
        "loot": ["Void Core", "Shadow Relic", "Soul Fragment"],
    },
}

